---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: reindexing-worker-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: esc-reindexing-worker
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Pods
      pods:
        metric:
          name: messages
        target:
          averageValue: "1"
          type: AverageValue
  behavior:
    scaleDown:
      policies:
        - type: Pods
          value: 1
          periodSeconds: 30
      selectPolicy: Min
      stabilizationWindowSeconds: 90
    scaleUp:
      policies:
        - type: Pods
          value: 1
          periodSeconds: 20
      selectPolicy: Max
      stabilizationWindowSeconds: 0
