alfresco-elasticsearch-connector:
  enabled: true
  reindexing:
    enabled: true

repository:
  replicaCount: 1
  extraLogStatements:
    org.alfresco.enterprise.license.LicenseComponent: debug
    org.alfresco.repo.importer.ImporterBootstrap: debug
  environment:
    JAVA_OPTS: " -Dindex.subsystem.name=elasticsearch
          -Dalfresco.cluster.enabled=true
          -Ddeployment.method=HELM_CHART
          -Dtransform.service.enabled=true
          -XX:MinRAMPercentage=50 -XX:MaxRAMPercentage=80"

alfresco-search:
  enabled: false

elasticsearch:
  enabled: true
kibana:
  enabled: false

