elasticsearch:
  enabled: true
kibana:
  enabled: false

alfresco-elasticsearch-connector:
  enabled: true
  reindexing:
    enabled: true
  elasticsearch:
    enabled: true
  kibana:
    enabled: false

alfresco-search:
  enabled: false

