# Defines the properties required by the search services (solr) app
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "content-services.fullname" . }}-solr-configmap
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
data:
  SOLR_ALFRESCO_HOST: "{{ template "content-services.fullname" . }}-repository"
  SOLR_ALFRESCO_PORT: "{{ .Values.repository.service.externalPort }}"
  SOLR_SOLR_HOST: "{{ template "content-services.fullname" . }}-solr"
  SOLR_SOLR_PORT: "{{ .Values.solr.image.internalPort }}"
  # The values for SOLR_CREATE_ALFRESCO_DEFAULTS and SOLR_OPTS, defined in the values.yaml for "solr" are set next:
  {{- if .Values.solr.environment }}
  {{- range $key, $val := .Values.solr.environment }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
  {{- end }}