# Defines the properties required by the share app
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "content-services.fullname" . }}-share-configmap
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
data:
  # The CATALINA_OPTS defined in the values.yaml file for the "share" are set here using proper quotes
  {{- if .Values.share.environment }}
  {{- range $key, $val := .Values.share.environment }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
  {{- end }}
  REPO_HOST: "{{ template "content-services.fullname" . }}-repository"
  REPO_PORT: "{{ .Values.repository.service.externalPort }}"