{{- if .Values.networkpolicysetting.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: imagemagick-allow-repository
spec:
  podSelector:
    matchLabels:
      app: {{ template "content-services.fullname" . }}-imagemagick
  policyTypes:
  - Ingress
  - Egress
  ingress:
    - from:
      - podSelector:
          matchLabels:
            app: {{ template "content-services.fullname" . }}-repository
      ports:
        - protocol: TCP
          port: 8090
        - protocol: TCP
          port: 80
  egress:
    - ports:
      - port: 53
        protocol: UDP
      - port: 53
        protocol: TCP
    - to:
      - podSelector:
          matchLabels:
            app: {{ template "content-services.fullname" . }}-imagemagick
{{- end }}
