{{- if .Values.networkpolicysetting.enabled }}
# Deny & block all traffic from outside & within the cluster
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-all
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  ingress: []
{{- end }}