{{- if .Values.networkpolicysetting.enabled }}
# Allow transform-router to communicate with activemq
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: activemq
spec:
  podSelector:
    matchLabels:
      {{ .Values.messageBroker.labelSelector }}
  policyTypes:
  - Ingress
  ingress:
    - from:
      - podSelector:
          matchLabels:
            app: {{ template "alfresco.shortname" . }}-router
{{- end }}