{{- if .Values.networkpolicysetting.enabled }}
# Allow transformers to communicate with filestore
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: filestore
spec:
  podSelector:
    matchLabels:
      app: {{ template "alfresco.shortname" . }}-filestore
  policyTypes:
  - Ingress
  ingress:
    - from:
      - podSelector:
          matchLabels:
            component: transformers
      ports:
        - protocol: TCP
          port: 8099
        - protocol: TCP
          port: 80
{{- end }}