{{- if .Values.networkpolicysetting.enabled }}
# Allow search in-bound traffic
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: search
spec:
  podSelector:
    matchLabels:
      app: {{ template "alfresco-search.host" . }}
  policyTypes:
  - Ingress
  # - Egress
  ingress:
    - from:
      # Allow repository to access search
      - podSelector:
          matchLabels:
            app: {{ template "content-services.fullname" . }}-repository

      # Allow nginx-ingress to access search
      - podSelector:
          matchLabels:
            app: nginx-ingress

      ports:
        - protocol: TCP
          port: 8983

    # # Allow nginx-ingress to access search
    # - from:
    #   - podSelector:
    #       matchLabels:
    #         app: nginx-ingress
    #   ports:
    #     - protocol: TCP
    #       port: 8983

{{- end }}