{{- if .Values.networkpolicysetting.enabled }}
# Allow only repository to connect database
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: database
spec:
  podSelector:
    matchLabels:
      app: {{ template "database.hostname" . }}
  policyTypes:
  - Ingress
  - Egress
  ingress:
    - from:
      - podSelector:
          matchLabels:
            app: {{ template "content-services.fullname" . }}-repository
      ports:
        - protocol: TCP
          port: {{ template "database.port" . }}
{{- end }}