{{- if .Values.networkpolicysetting.enabled }}
# Allow transformers to be accessed by repository
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: transformers
spec:
  podSelector:
    matchLabels:
      component: transformers
  policyTypes:
  - Ingress
  # - Egress
  ingress:
    - from:
      - podSelector:
          matchLabels:
            app: {{ template "content-services.fullname" . }}-repository
      ports:
        - protocol: TCP
          port: 8090
        - protocol: TCP
          port: 80

{{- end }}